### ISSUE TITLE
3-rstudiobasics - add motivation for Desktop (v Server)

### ISSUE THREAD

**Issue by RhoBott** [ismayc/rbasics-book#6]
I agree (for a variety of reasons), and also -- curious re: what you would cite as reasons for this.

> After you complete a few months of work with the RStudio Server, it is recommended that you download RStudio Desktop to your computer.

**Comment by ismayc** [comment]
This book was written 3 years ago now and I’d like to do a full rewrite at some point, but that won’t happen this year probably. The server is valuable since installation is really hard for beginners, even with something pretty foolproof like R and RStudio where you just push the buttons for the most part.

**Comment by RhoBott** [comment]
> This book was written 3 years ago now and I’d like to do a full rewrite at some point, but that won’t happen this year probably. 

Keep me posted; maybe we can collaborate on that...
